webtalk_init -webtalk_dir E:/Miz702/miz702_sys/miz702_sys.hw/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat Apr 09 14:44:06 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "Vivado v2015.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "1412921" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "labtool" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "19f5c235aaa753ea908b9f25e877eff6" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "def31685-f8f2-4df3-a533-070936d6efdb" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-2430M CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client labtool
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400003727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400003727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "00:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key chain -value "0000400003727093" -context "labtool\\usage"
webtalk_add_data -client labtool -key pgmcnt -value "01:00:00" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_add_data -client labtool -key cable -value "Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:Xilinx/Port_#0002.Hub_#0004/DLC9-Port_#0002.Hub_#0004/6000000:" -context "labtool\\usage"
webtalk_transmit -clientid 3300809017 -regid "" -xml E:/Miz702/miz702_sys/miz702_sys.hw/webtalk/usage_statistics_ext_labtool.xml -html E:/Miz702/miz702_sys/miz702_sys.hw/webtalk/usage_statistics_ext_labtool.html -wdm E:/Miz702/miz702_sys/miz702_sys.hw/webtalk/usage_statistics_ext_labtool.wdm -intro "<H3>LABTOOL Usage Report</H3><BR>"
webtalk_terminate
