# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.cache/wt [current_project]
set_property parent.project_path E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property ip_repo_paths {
  e:/miz702/miz702_ip_core/axis2vga
  e:/miz702/miz702_ip_core/miz702_vtc_1.0
  e:/Miz702/miz702_ip_core
} [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_axi_vdma_0_0/system_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_axis2vga_0_0/src/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_25M_1/system_rst_processing_system7_0_25M_1_board.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_25M_1/system_rst_processing_system7_0_25M_1.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_rst_processing_system7_0_25M_1/system_rst_processing_system7_0_25M_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_xbar_2/system_xbar_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_auto_pc_0/system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/ip/system_auto_pc_1/system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/system.bd]

read_verilog -library xil_defaultlib E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/sources_1/bd/system/hdl/system_wrapper.v
read_xdc E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/constrs_1/new/miz702.xdc
set_property used_in_implementation false [get_files E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/constrs_1/new/miz702.xdc]

read_xdc E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/constrs_1/new/debug.xdc
set_property used_in_implementation false [get_files E:/Miz702/Miz702_Sys_MedianFilter/miz702_sys.srcs/constrs_1/new/debug.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top system_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef system_wrapper.dcp
catch { report_utilization -file system_wrapper_utilization_synth.rpt -pb system_wrapper_utilization_synth.pb }
