# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/MIZ702/CH29/ip_repo/OV5640_IP_ML/OV5640_IP_ML.cache/wt [current_project]
set_property parent.project_path D:/MIZ702/CH29/ip_repo/OV5640_IP_ML/OV5640_IP_ML.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
read_verilog -library xil_defaultlib {
  D:/MIZ702/CH29/ip_repo/OV5640_IP_ML/SRC/I2C_OV5640_RGB565_Config.v
  D:/MIZ702/CH29/ip_repo/OV5640_IP_ML/SRC/i2c_timing_ctrl.v
  D:/MIZ702/CH29/ip_repo/OV5640_IP_ML/SRC/count_reset_v1.v
  D:/MIZ702/CH29/ip_repo/OV5640_IP_ML/SRC/cmos_decode_v1.v
  D:/MIZ702/CH29/ip_repo/OV5640_IP_ML/SRC/OV5640_ML_IP.v
}
synth_design -top OV5640_IP_ML -part xc7z020clg484-1
write_checkpoint -noxdef OV5640_IP_ML.dcp
catch { report_utilization -file OV5640_IP_ML_utilization_synth.rpt -pb OV5640_IP_ML_utilization_synth.pb }
